# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('error', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('vehicle_trailer', models.CharField(choices=[('Please Select', 'Please Select'), ('Truck', 'Truck'), ('Trailer', 'Trailer')], default='Please Select', max_length=50)),
                ('title', models.CharField(choices=[('Please Select', 'Please Select'), ('MOT', 'MOT'), ('Tax', 'Tax'), ('Maintenance Check', 'Maintenance Check')], default='Please Select', max_length=20)),
                ('date', models.DateField(null=True, blank=True)),
                ('created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.TimeField(null=True)),
                ('notes', models.CharField(null=True, max_length=50)),
                ('reminder', models.BooleanField(default=False)),
                ('author', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('trailer_Number', models.CharField(null=True, max_length=40)),
                ('trailer_Type', models.CharField(choices=[('Please Select', 'Please Select'), ('Bulk Tipping', 'Bulk Tipping'), ('Car Transporter', 'Car Transporter'), ('Crane', 'Crane'), ('Curtain Side', 'Curtain Side'), ('Drawbar', 'Drawbar'), ('Ejector', 'Ejector'), ('Flat', 'Flat'), ('Livestock Carrier', 'Livestock Carrier'), ('Low Loader', 'Low Loader'), ('Moving Floor', 'Moving Floor'), ('Refrigerated', 'Refrigerated'), ('Skeletal', 'Skeletal'), ('Skip', 'Skip'), ('Step Frame', 'Step Frame'), ('Tanker', 'Tanker'), ('Tipper Crane', 'Tipper Crane')], default='Please Select', max_length=15)),
                ('trailer_Year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='year')),
                ('created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('vehicle_Reg', models.CharField(null=True, max_length=40)),
                ('make', models.CharField(choices=[('Please Select', 'Please Select'), ('Bedford', 'Bedford'), ('Daf', 'Daf'), ('ERF', 'ERF'), ('Foden', 'Foden'), ('Freightliner', 'Freightliner'), ('Isuzu', 'Isuzu'), ('Iveco', 'Iveco'), ('Kenworth', 'Kenworth'), ('Leyland', 'Leyland'), ('Mack', 'Mack'), ('Man', 'Man'), ('Mercedes', 'Mercedes'), ('Peterbilt', 'Peterbilt'), ('Renault', 'Renault'), ('Scammell', 'Scammell'), ('Scania', 'Scania'), ('Volvo', 'Volvo')], default='Please Select', max_length=15)),
                ('model', models.CharField(choices=[('Please Select', 'Please Select'), ('Axor', 'Axor'), ('FH Globetrotter', 'FH Globetrotter'), ('LF45', 'LF45'), ('Magnum', 'Magnum'), ('R420', 'R420'), ('R440', 'R440'), ('R480', 'R480'), ('Stralis', 'Stralis'), ('TGM', 'TGM'), ('TGX', 'TGX'), ('XF105', 'XF105'), ('65', '65'), ('105510', '105510')], default='Please Select', max_length=40)),
                ('year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='year')),
                ('created_Date', models.DateField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('address', models.TextField(null=True, blank=True, max_length=500)),
                ('make', models.CharField(choices=[('Please Select', 'Please Select'), ('Bedford', 'Bedford'), ('Daf', 'Daf'), ('ERF', 'ERF'), ('Foden', 'Foden'), ('Freightliner', 'Freightliner'), ('Isuzu', 'Isuzu'), ('Iveco', 'Iveco'), ('Kenworth', 'Kenworth'), ('Leyland', 'Leyland'), ('Mack', 'Mack'), ('Man', 'Man'), ('Mercedes', 'Mercedes'), ('Peterbilt', 'Peterbilt'), ('Renault', 'Renault'), ('Scammell', 'Scammell'), ('Scania', 'Scania'), ('Volvo', 'Volvo')], default='Please Select', max_length=100)),
                ('model', models.CharField(choices=[('Please Select', 'Please Select'), ('Axor', 'Axor'), ('FH Globetrotter', 'FH Globetrotter'), ('LF45', 'LF45'), ('Magnum', 'Magnum'), ('R420', 'R420'), ('R440', 'R440'), ('R480', 'R480'), ('Stralis', 'Stralis'), ('TGM', 'TGM'), ('TGX', 'TGX'), ('XF105', 'XF105'), ('65', '65'), ('105510', '105510')], default='Please Select', max_length=100)),
                ('fleet_Number', models.CharField(choices=[(0.0, 'Please Select'), (1.0, 'One'), (2.0, 'Two'), (3.0, 'Three'), (4.0, 'Four')], default='Please Select', max_length=100)),
                ('odo_Reading', models.CharField(null=True, max_length=40)),
                ('chassis', models.CharField(null=True, max_length=40)),
                ('tachograph_Calibration', models.DateField(default=django.utils.timezone.now)),
                ('ved_Expiry', models.DateField(default=django.utils.timezone.now)),
                ('last_Two_Year_Date', models.DateField(default=django.utils.timezone.now)),
                ('inspection_Date', models.DateField(default=django.utils.timezone.now)),
                ('dFT_Plate_Condition_Details', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('speed_Limiter_Plate_Condition_Details', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('seat_Belts_Supplementary_Restraint_Systems_Condition', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Floor_and_Steps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('seats_Driver_Seat_All_Adjustments_Fully_Functional', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('other_Seats_and_Crew_Amenities', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('mirrors_Internal', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('view_To_Front', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('condition_Of_Glass', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('screen_Wipers', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('speedometer', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('engine_Tachometer', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('audible_Warning', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('driving_Controls', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Wheel_Free', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Wheel_Security', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Column', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('anti_Theft', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('pressure_Warning', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('pressure_Build', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('other_Gauges', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('hand_Lever', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('service_Brake', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('service_Brake_ABS', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('hand_Operated_Brake', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('electrical_Wiring', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('front_Fog', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('panel', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Heater', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('bumper', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('condition_Of_Wings', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Panels', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Security', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Doors', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cab_Floor', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('mirrors_and_Indirect', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('front_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('headlamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('spot_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('engine_Mountings', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('oil_Leaks', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('fuel_Tanks', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('exhaust_Systems', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('exhaust_Brakes', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('radiator_Mounting', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cooling_System', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('fan', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('fuel_Pump', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('speed_Limiter', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('injectors', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('air_Intake', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('air_Compressor', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('road_Wheels', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('sideguards', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('spare_Wheel', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('vehicle_To_Trailer', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('condition_Of_Wings_Back', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('security_Of_Body', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('demountable_Bodies', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('security_Of_Containers', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('tipping_Gear', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('tailboard', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('cranes', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('ancillary_Equipment', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('condition_Of_Chassis', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('wiring_Electrical', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('electrical_Connections', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('leak_Oil', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('fuel_Tanks_Systems', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('exhaust_System', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('suspension_Pins', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('suspension_Units', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('spring_Units', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('shock_Absorbers', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('wheel_Bearings', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('stub_Axle', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Mechanism', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Alignment', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('steering_Gear', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('power_Steering', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('axle_Alignment', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('clutch_Operation', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('gearbox', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('changing_Speed', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('power_Take', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('final_Drive', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('speed_Shift', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('differential_Lock', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('load_Transfer', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('transmission', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('electronic_Braking', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('hydraulic_Fluid', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('mechanical_Brake', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('drum_Lining', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('brake_Actuators', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('brake_Systems', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('trailer_Coupling', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('load_Sensing', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('air_Brake', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('anti_Lock', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('supply_Dump', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('multi_Circuit', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('braking_Devices', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('rear_Marking', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('rear_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('rear_Fog', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('reflectors', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('direction_Indicators', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('side_Marker', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('stop_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('reversing_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('position_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('other_Lamps', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('paintwork', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('licences', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('legal_Writing', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('reg_Plates', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('other_Dangerous', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('smoke_Emission', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('size_Of_Tyre', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('condition_Of_Tyre', models.CharField(choices=[('Please Select', 'Please Select'), ('Serviceable', 'Serviceable'), ('Item Requires Attention', 'Item Requires Attention'), ('Not Checked', 'Not Checked'), ('Not Applicable', 'Not Applicable')], default='Please Select', max_length=100)),
                ('attention', models.CharField(null=True, blank=True, max_length=40)),
                ('done_By', models.CharField(null=True, blank=True, max_length=40)),
                ('action', models.CharField(null=True, blank=True, max_length=250)),
                ('imo_No', models.CharField(null=True, blank=True, max_length=40)),
                ('signature_Of_Inspector', models.TextField(null=True, blank=True, max_length=500)),
                ('signature', models.CharField(null=True, blank=True, max_length=40)),
                ('position', models.CharField(null=True, blank=True, max_length=40)),
                ('comments', models.TextField(null=True, blank=True, max_length=500)),
                ('percent', models.CharField(null=True, blank=True, max_length=4)),
                ('test', models.CharField(null=True, blank=True, max_length=40)),
                ('road_Speed', models.CharField(choices=[('Please Select', 'Please Select'), ('Yes', 'Yes'), ('No', 'No')], default='Please Select', max_length=100)),
                ('speed', models.CharField(null=True, blank=True, max_length=4)),
                ('road_Test', models.TextField(null=True, blank=True, max_length=500)),
                ('options', models.CharField(choices=[('Please Select', 'Please Select'), ('Yes', 'Yes'), ('No', 'No')], default='Please Select', max_length=100)),
                ('date_Completed', models.DateField(default=django.utils.timezone.now)),
                ('created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('company_Name', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='truckmaintenance',
            name='company_Name',
            field=models.ForeignKey(to='TrackaTruck.UserProfile', null=True),
        ),
        migrations.AddField(
            model_name='truckmaintenance',
            name='vehicle_Reg',
            field=models.ForeignKey(to='TrackaTruck.Truck', default='Please Select', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='trailer_Number',
            field=models.ForeignKey(to='TrackaTruck.Trailer', null=True, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_Reg',
            field=models.ForeignKey(to='TrackaTruck.Truck', null=True, max_length=100),
        ),
    ]
